# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: "$(Date:yyyy)-$(Date:MM)-$(Rev:r)"

pr:
- main

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - src/*
    - tests/*
    - prisma/*

pool:
  vmImage: ubuntu-latest
  
steps:
- script: echo Hello, world!
